spring.application.name=service-registry

server.port=8761

eureka.instance.hostname=localhost

server.servlet.context-path=/registry



# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
