spring.application.name=config-server


server.port=9999

spring.datasource.url= jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=170804

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect,

server.servlet.context-path=/configserver

spring.cloud.config.server.git.uri=https://github.com/mohansaivenkat/prac-config-server.git